// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMya50YPcHoXXDaufeID1bDXexaSyOaE',
    appId: '1:825794293903:web:08345e912820622eb200fa',
    messagingSenderId: '825794293903',
    projectId: 'crud-app-1d1dd',
    authDomain: 'crud-app-1d1dd.firebaseapp.com',
    storageBucket: 'crud-app-1d1dd.firebasestorage.app',
    measurementId: 'G-24GZT0NTVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQSWMKUrxOxs-hP6tA-ztfR9R7sPO8Vo',
    appId: '1:825794293903:android:e850d748391febe6b200fa',
    messagingSenderId: '825794293903',
    projectId: 'crud-app-1d1dd',
    storageBucket: 'crud-app-1d1dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDigpXY5Ousv8xlmc9xvXjCGOHBFdXwokY',
    appId: '1:825794293903:ios:2dfde83040039780b200fa',
    messagingSenderId: '825794293903',
    projectId: 'crud-app-1d1dd',
    storageBucket: 'crud-app-1d1dd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDigpXY5Ousv8xlmc9xvXjCGOHBFdXwokY',
    appId: '1:825794293903:ios:2dfde83040039780b200fa',
    messagingSenderId: '825794293903',
    projectId: 'crud-app-1d1dd',
    storageBucket: 'crud-app-1d1dd.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgMya50YPcHoXXDaufeID1bDXexaSyOaE',
    appId: '1:825794293903:web:352808adc3842438b200fa',
    messagingSenderId: '825794293903',
    projectId: 'crud-app-1d1dd',
    authDomain: 'crud-app-1d1dd.firebaseapp.com',
    storageBucket: 'crud-app-1d1dd.firebasestorage.app',
    measurementId: 'G-J1SCQZ3ECR',
  );
}
